SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    TOTAL_SALES,
    TOTAL_ORDERS,
    AVERAGE_ORDER_VALUE

FROM {{ ref('rdl_customer_sales') }}

WHERE TOTAL_SALES > 50000

ORDER BY TOTAL_SALES DESC