SELECT
    CATEGORY,

    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,

    SUM(QUANTITY) AS TOTAL_QUANTITY,

    SUM(ORDER_AMOUNT) AS TOTAL_SALES,

    AVG(ORDER_AMOUNT) AS AVG_ORDER_VALUE

FROM {{ ref('cdl_customer_orders') }}

WHERE ORDER_STATUS <> '{{ var("cancelled_status") }}'

GROUP BY CATEGORY