SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,

    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,

    SUM(QUANTITY) AS TOTAL_ITEMS,

    SUM(ORDER_AMOUNT) AS TOTAL_SALES,

    AVG(ORDER_AMOUNT) AS AVERAGE_ORDER_VALUE

FROM {{ ref('cdl_customer_orders') }}

WHERE ORDER_STATUS <> 'Cancelled'

GROUP BY
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE